
name: build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: cache
          path: |
            node_modules
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i && npm run build
